[tox]
requires = tox-uv>=1
env_list = lint, py310, py311, py312, py313

[testenv]
runner = uv-venv-runner
extras = dev
set_env =
    KIVY_NO_ARGS = 1
commands =
    pytest {posargs}

[testenv:lint]
runner = uv-venv-runner
skip_install = true
deps =
    ruff
commands =
    ruff check .
    ruff format --check --diff .
